
#WIN8_PRINT_ENABLED=False
#WIN8_SCREEN_ORIENTATION=15			'bitwise OR of: 1=portrait, 2=landscape, 4=portrait flipped, 8=landscape flipped

#OPENGL_GLES20_ENABLED=False
#OPENGL_DEPTH_BUFFER_ENABLED=False

#MOJO_AUTO_SUSPEND_ENABLED=False
#MOJO_IMAGE_FILTERING_ENABLED=True

#TEXT_FILES="*.txt|*.xml|*.json"
#IMAGE_FILES="*.png|*.jpg"
#SOUND_FILES="*.wav"
#MUSIC_FILES="*.wav|*.mp3"
#BINARY_FILES="*.bin|*.dat"
